/* Generated by tools/gen_frames.py from assets/frames. Do not edit. */
#pragma once
#include <stdint.h>

#define FRAME_PHOTO_X 16
#define FRAME_PHOTO_W 128
#define FRAME_PHOTO_H 112

typedef enum {
    FRAME_BLACK,
    FRAME_CORNERBRACKET,
    FRAME_CORNERFRAMEBLACK,
    FRAME_DASHES,
    FRAME_PIXELBOY,
    FRAME_COUNT
} frame_id_t;

/* w/h: full canvas size (160x144 or 160x224). photo_y: where the
 * 128x112 photo window starts (x is always FRAME_PHOTO_X). indices:
 * h rows of w hardware-shade values (0..3, see gen_frames.py). */
typedef struct { int w, h, photo_y; const uint8_t *indices; } frame_meta_t;
extern const frame_meta_t frame_meta[FRAME_COUNT];
extern const char *const frame_names[FRAME_COUNT];
