/* Generated by tools/gen_icons.py from assets/icons. Do not edit. */
#pragma once

#define ICON_W 16
#define ICON_H 16

typedef enum {
    ICON_PALETTE,
    ICON_DITHER,
    ICON_STYLE,
    ICON_SIZE,
    ICON_AMOUNT,
    ICON_GALLERY,
    ICON_EXIT,
    ICON_FRAME,
    ICON_COUNT
} icon_id_t;
