"""
Generates components/gbcam/src/dc_lut_data.h: a precomputed nearest-palette-
colour lookup table for every Dither Cam palette, so dc_quantize()'s hot path
(dithercam.c's nearest()) becomes an O(1) array read instead of an O(n) scan
over up to 64 palette colours per pixel - the difference between comfortably
hitting 15 fps on the ESP32-P4 and not, at the largest resolution/palette
combos (see PLAN.md's Floyd-Steinberg perf note).

Reads the same source .hex files as tools/gen_palettes.py (not the generated
palettes_data.h) so this is independent of that script's run order, and uses
the exact same weighted distance dithercam.c's nearest() uses (2*dr^2+4*dg^2+
3*db^2), so the LUT always agrees with what a full scan would have picked at
each bucket's representative colour.

    python tools/gen_dc_lut.py

DC_LUT_BITS=5 (32 levels/channel, 32768 entries/palette) keeps the visible
quantization error tiny - half a bucket width (4 codes/channel) - while
costing 32 KiB/palette. All DC_PALETTE_COUNT palettes together: ~1 MiB flash,
comfortable on the 16 MiB flash this board is configured for.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "PIXEL CAM", "xiao-pixelcam", "sd_card", "palettes", "dithercam")
OUT = os.path.join(ROOT, "components", "gbcam", "src", "dc_lut_data.h")

LUT_BITS = 5
LUT_LEVELS = 1 << LUT_BITS
LUT_SIZE = LUT_LEVELS ** 3


def read_hex(path):
    cols = []
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.fullmatch(r"#?([0-9a-fA-F]{6})", line[:7].strip())
        if m:
            v = int(m.group(1), 16)
            cols.append(((v >> 16) & 255, (v >> 8) & 255, v & 255))
    return cols


def load_palettes():
    out = []
    for f in sorted(os.listdir(SRC)):
        if f.lower().endswith(".hex"):
            cols = read_hex(os.path.join(SRC, f))
            if 2 <= len(cols) <= 64:
                out.append((f[:-4], cols))
    return out


def nearest_index(r, g, b, cols):
    """Same weighted distance as dithercam.c's nearest(): 2*dr^2+4*dg^2+3*db^2."""
    best, best_d = 0, None
    for i, (cr, cg, cb) in enumerate(cols):
        dr, dg, db = r - cr, g - cg, b - cb
        d = 2 * dr * dr + 4 * dg * dg + 3 * db * db
        if best_d is None or d < best_d:
            best, best_d = i, d
            if d == 0:
                break
    return best


def bucket_center(level):
    """Representative colour for quantized code `level` (0..LUT_LEVELS-1):
    the centre of the 256/LUT_LEVELS-wide band it covers, matching how the
    runtime derives the same index from an 8-bit channel (top LUT_BITS bits)."""
    span = 256 // LUT_LEVELS
    return level * span + span // 2


def main():
    palettes = load_palettes()
    centers = [bucket_center(i) for i in range(LUT_LEVELS)]

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/gen_dc_lut.py. Do not edit.\n")
        f.write(" * Precomputed nearest-palette-colour index for every Dither Cam palette,\n")
        f.write(f" * quantized to {LUT_BITS} bits/channel ({LUT_LEVELS} levels, {LUT_SIZE} entries/palette).\n")
        f.write(" * See that script's docstring for why this exists and how to regenerate it.\n")
        f.write(" * DC_LUT_BITS/DC_LUT_SIZE are dithercam.h's, not redefined here - this file\n")
        f.write(" * is only ever included after it (see dithercam.c). */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"static const uint8_t dc_palette_lut[{len(palettes)}][DC_LUT_SIZE] = {{\n")
        for name, cols in palettes:
            f.write(f"/* {name} ({len(cols)} colours) */\n{{")
            row = []
            for ri in range(LUT_LEVELS):
                r = centers[ri]
                for gi in range(LUT_LEVELS):
                    g = centers[gi]
                    for bi in range(LUT_LEVELS):
                        b = centers[bi]
                        row.append(nearest_index(r, g, b, cols))
            f.write(",".join(map(str, row)))
            f.write("},\n")
        f.write("};\n")

    total_bytes = len(palettes) * LUT_SIZE
    print(f"{len(palettes)} palettes x {LUT_SIZE} entries = {total_bytes} bytes "
          f"({total_bytes / 1024:.0f} KiB) -> {OUT}")


if __name__ == "__main__":
    main()
