"""
Generates firmware/main/frames.h and firmware/main/frames_data.h from
assets/frames/*.png - decorative borders for GB Camera photos, ported from
PixelBoy's own Android app (engine/frames/CustomFramePng.kt's load()).

    python tools/gen_frames.py

Each PNG is a 160x144 ("Standard", 2-tile top/bottom margin) or 160x224
("Wild", 5-tile top / 9-tile bottom margin) RGBA canvas with a 128x112 photo
window - the window's own pixels are ignored (frame_compose() always
overwrites them with the real photo), so leave it blank or transparent,
whichever's easiest to draw against. Every other pixel is flattened onto
white by its alpha (a half-transparent edge reads as "toward white", not
black) then thresholded to one of the 4 hardware shade levels (0 = lightest
.. 3 = darkest) with PIL's ITU-R 601-2 luma weights, matching
CustomFramePng.kt exactly so a frame looks the same on both apps.

To import frames from the original cartridge ROM's own format
(framegroup_*.json - copyrighted, never committed, see .gitignore) use
tools/import_gb_frames.py first, which writes standard-size PNGs into
assets/frames/ for this script to pick up.
"""
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "assets", "frames")
PUB = os.path.join(ROOT, "firmware", "main", "frames.h")
DATA = os.path.join(ROOT, "firmware", "main", "frames_data.h")

CANVAS_W = 160
TILE_PX = 8
PHOTO_X = 2 * TILE_PX   # left margin is always 2 tiles, both canvas sizes
PHOTO_W, PHOTO_H = 128, 112
# canvas height in px -> top margin in tiles (must match CustomFramePng.kt's
# CUSTOM_LAYOUTS and FramePackParser's PHOTO_H_TILES=14 exactly).
LAYOUTS = {144: 2, 224: 5}  # "Standard", "Wild"


def enum_name(stem):
    return "FRAME_" + "".join(c.upper() if c.isalnum() else "_" for c in stem)


def quantize(img):
    w, h = img.size
    upper_rows = LAYOUTS.get(h)
    if w != CANVAS_W or upper_rows is None:
        sizes = ", ".join(f"{CANVAS_W}x{hh}" for hh in LAYOUTS)
        raise SystemExit(f"assets/frames image is {w}x{h}, expected one of: {sizes}")
    photo_y = upper_rows * TILE_PX

    px = img.convert("RGBA").load()
    rows = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b, a = px[x, y]
            # Flatten transparency onto white first - see module docstring.
            fr = (r * a + 255 * (255 - a)) / 255
            fg = (g * a + 255 * (255 - a)) / 255
            fb = (b * a + 255 * (255 - a)) / 255
            gray = fr * 0.299 + fg * 0.587 + fb * 0.114
            level = min(3, max(0, round(gray / 64.0)))
            row.append(3 - level)  # hardware convention: 0 = lightest
        rows.append(row)
    return rows, photo_y


def main():
    stems = sorted(f[:-4] for f in os.listdir(SRC_DIR) if f.lower().endswith(".png"))
    if not stems:
        raise SystemExit(f"no .png files in {SRC_DIR}")

    frames = []
    for stem in stems:
        img = Image.open(os.path.join(SRC_DIR, f"{stem}.png"))
        rows, photo_y = quantize(img)
        frames.append((enum_name(stem), stem, rows, photo_y))

    with open(PUB, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/gen_frames.py from assets/frames. Do not edit. */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define FRAME_PHOTO_X {PHOTO_X}\n")
        f.write(f"#define FRAME_PHOTO_W {PHOTO_W}\n")
        f.write(f"#define FRAME_PHOTO_H {PHOTO_H}\n\n")
        f.write("typedef enum {\n")
        for enum, _, _, _ in frames:
            f.write(f"    {enum},\n")
        f.write("    FRAME_COUNT\n} frame_id_t;\n\n")
        f.write("/* w/h: full canvas size (160x144 or 160x224). photo_y: where the\n"
                " * 128x112 photo window starts (x is always FRAME_PHOTO_X). indices:\n"
                " * h rows of w hardware-shade values (0..3, see gen_frames.py). */\n")
        f.write("typedef struct { int w, h, photo_y; const uint8_t *indices; } frame_meta_t;\n")
        f.write("extern const frame_meta_t frame_meta[FRAME_COUNT];\n")
        f.write("extern const char *const frame_names[FRAME_COUNT];\n")

    with open(DATA, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/gen_frames.py from assets/frames. Do not edit. */\n")
        f.write("#include \"frames.h\"\n\n")
        for enum, stem, rows, _ in frames:
            flat = [v for row in rows for v in row]
            f.write(f"static const uint8_t {enum.lower()}_indices[{len(flat)}] = {{\n")
            for i in range(0, len(flat), 32):
                f.write("    " + ", ".join(str(v) for v in flat[i:i + 32]) + ",\n")
            f.write("};\n")
        f.write("\nconst frame_meta_t frame_meta[FRAME_COUNT] = {\n")
        for enum, stem, rows, photo_y in frames:
            h = len(rows)
            f.write(f"    {{{CANVAS_W}, {h}, {photo_y}, {enum.lower()}_indices}}, /* {stem} */\n")
        f.write("};\n\n")
        f.write("const char *const frame_names[FRAME_COUNT] = {\n")
        for _, stem, _, _ in frames:
            f.write(f'    "{stem.upper()[:12]}",\n')
        f.write("};\n")

    print(f"{len(frames)} frame(s) -> {PUB}, {DATA}")


if __name__ == "__main__":
    main()
