"""
Generates firmware/main/font8x8.h from early-gameboy.ttf ("Early GameBoy" - a true
8x8 pixel font, not a vector font that needs hinting tricks: at 8pt it renders
pixel-perfect, one font unit per output pixel, monospace advance 8 for every
printable glyph). Covers the same 0x20 (space) .. 0x5F (underscore) range
font5x7.h did - uppercase + digits + punctuation - since like that font,
display_text() upper-cases lowercase input before drawing (this TTF's own
lowercase glyphs render identically to uppercase anyway, so nothing is lost).

early-gameboy.ttf is missing glyphs for several punctuation codepoints the app
actually formats into strings (# for the photo counter, % for Dither Cam's
amount readout, plus a handful more nothing currently uses but might later) -
FreeType silently renders those as blank. Rather than have those go invisible,
this falls back to font5x7.h's existing glyph for anything that comes back
blank (other than space, which is legitimately blank), nearest-scaled from
5x7 into the 8x8 cell - a little less crisp than the rest of the font, but
present and readable instead of missing.

    python tools/gen_font.py

Output format mirrors font5x7.h exactly (column-major bytes, bit 0 = top row)
so app_display.c's display_text()/display_text_width() only need their glyph
width/height constants updated, not their bit-plotting logic.
"""
import os
import re

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF = os.path.join(ROOT, "early-gameboy.ttf")
OLD_FONT = os.path.join(ROOT, "firmware", "main", "font5x7.h")
OUT = os.path.join(ROOT, "firmware", "main", "font8x8.h")

SIZE = 8  # native pixel size - see module docstring
FIRST, LAST = 0x20, 0x5F


def glyph_columns(font, ch: str) -> list[int]:
    img = Image.new("L", (SIZE, SIZE), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
    px = img.load()
    cols = []
    for x in range(SIZE):
        b = 0
        for y in range(SIZE):
            if px[x, y] >= 128:
                b |= 1 << y
        cols.append(b)
    return cols


def load_old_font5x7() -> dict[int, list[int]]:
    """Parses the existing font5x7.h array (5 columns x 7 rows, bit 0 = top)
    for the nearest-scale fallback - see module docstring."""
    text = open(OLD_FONT, encoding="utf-8").read()
    rows = re.findall(r"\{((?:0x[0-9A-Fa-f]{2}, ?){4}0x[0-9A-Fa-f]{2})\}", text)
    return {FIRST + i: [int(v, 16) for v in row.split(",")] for i, row in enumerate(rows)}


def nearest_scale_5x7_to_8x8(cols5x7: list[int]) -> list[int]:
    cols8 = []
    for x in range(SIZE):
        sx = min(x * 5 // SIZE, 4)
        src = cols5x7[sx]
        b = 0
        for y in range(SIZE):
            sy = min(y * 7 // SIZE, 6)
            if src & (1 << sy):
                b |= 1 << y
        cols8.append(b)
    return cols8


def main():
    font = ImageFont.truetype(TTF, SIZE)
    old_font = load_old_font5x7()
    glyphs = []
    fallback_count = 0
    for code in range(FIRST, LAST + 1):
        cols = glyph_columns(font, chr(code))
        if code != ord(" ") and all(c == 0 for c in cols) and code in old_font:
            cols = nearest_scale_5x7_to_8x8(old_font[code])
            fallback_count += 1
        glyphs.append(cols)
    print(f"{fallback_count} glyph(s) missing from {os.path.basename(TTF)}, "
          f"filled in from font5x7.h")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"/* Generated by tools/gen_font.py from {os.path.basename(TTF)}"
                f" (\"Early GameBoy\"), {SIZE}x{SIZE}, ASCII 0x{FIRST:02X}..0x{LAST:02X}"
                " (space .. underscore).\n")
        f.write(" * Column-major, bit 0 = top row - same convention font5x7.h used, just"
                f" {SIZE}x{SIZE} cells instead of 5x7. Lower-case is drawn as upper case\n")
        f.write(" * (see display_text()) - this font's own lower-case glyphs render identically"
                " to upper-case anyway. Do not edit by hand. */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define FONT8X8_FIRST 0x{FIRST:02X}\n")
        f.write(f"#define FONT8X8_LAST  0x{LAST:02X}\n\n")
        f.write(f"static const uint8_t font8x8[FONT8X8_LAST - FONT8X8_FIRST + 1][{SIZE}] = {{\n")
        for code, cols in zip(range(FIRST, LAST + 1), glyphs):
            ch = chr(code)
            label = ch if ch not in ("\\", "'") else "\\" + ch
            row = ", ".join(f"0x{b:02X}" for b in cols)
            f.write(f"    {{{row}}}, /* '{label}' */\n")
        f.write("};\n")

    print(f"{len(glyphs)} glyphs, {SIZE}x{SIZE} -> {OUT}")


if __name__ == "__main__":
    main()
