"""
Generates components/gbcam/include/gbcam_palettes.h and
components/gbcam/src/palettes_data.h from the PIXEL CAM palette exports
(PIXEL CAM/xiao-pixelcam/sd_card/palettes/{gb,dithercam}/*.hex).

    python tools/gen_palettes.py

GB palettes are 4 colours, stored dark -> light in the .hex files; gbcam
shades run 0 = lightest .. 3 = darkest, so they are reversed here.
Dither Cam palettes are any length (up to 64), any order.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "PIXEL CAM", "xiao-pixelcam", "sd_card", "palettes")
PUB = os.path.join(ROOT, "components", "gbcam", "include", "gbcam_palettes.h")
DATA = os.path.join(ROOT, "components", "gbcam", "src", "palettes_data.h")
GB_DEFAULT = "grayscale"
DC_DEFAULT = "c64"   # PIXEL CAM's Dither Cam default


def read_hex(path):
    cols = []
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.fullmatch(r"#?([0-9a-fA-F]{6})", line[:7].strip())
        if m:
            v = int(m.group(1), 16)
            cols.append(((v >> 16) & 255, (v >> 8) & 255, v & 255))
    return cols


def load(sub):
    d = os.path.join(SRC, sub)
    out = []
    for f in sorted(os.listdir(d)):
        if f.lower().endswith(".hex"):
            out.append((f[:-4], read_hex(os.path.join(d, f))))
    return out


def label(name):
    return name.replace("_", " ").upper()[:12]


gb = [(n, c) for n, c in load("gb") if len(c) == 4]
dc = [(n, c) for n, c in load("dithercam") if 2 <= len(c) <= 64]
gb_default = next(i for i, (n, _) in enumerate(gb) if n == GB_DEFAULT)
dc_default = next(i for i, (n, _) in enumerate(dc) if n == DC_DEFAULT)

with open(PUB, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by tools/gen_palettes.py from the PIXEL CAM palette exports. Do not edit. */\n")
    f.write("#pragma once\n\n")
    f.write(f"#define GBCAM_PALETTE_COUNT {len(gb)}\n")
    f.write(f"#define GBCAM_PALETTE_DEFAULT {gb_default}  /* {GB_DEFAULT} */\n")
    f.write(f"#define DC_PALETTE_COUNT {len(dc)}\n")
    f.write(f"#define DC_PALETTE_DEFAULT {dc_default}  /* {DC_DEFAULT} */\n")
    f.write("#define DC_PALETTE_MAX_COLORS 64\n")

with open(DATA, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by tools/gen_palettes.py from the PIXEL CAM palette exports. Do not edit. */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("/* GB palettes: shade 0 (lightest) .. 3 (darkest), RGB888. */\n")
    f.write(f"static const uint8_t gb_palette_rgb[{len(gb)}][4][3] = {{\n")
    for name, cols in gb:
        rev = list(reversed(cols))
        f.write("    {" + ", ".join("{0x%02X, 0x%02X, 0x%02X}" % c for c in rev) + f"}}, /* {name} */\n")
    f.write("};\n")
    f.write(f"static const char *const gb_palette_names[{len(gb)}] = {{\n")
    f.write("".join(f'    "{label(n)}",\n' for n, _ in gb))
    f.write("};\n\n")
    f.write("/* Dither Cam palettes: n colours each, RGB888, flattened. */\n")
    offs, flat = [], []
    for _, cols in dc:
        offs.append(len(flat))
        flat.extend(cols)
    f.write(f"static const uint8_t dc_palette_rgb[{len(flat)}][3] = {{\n")
    for i in range(0, len(flat), 6):
        f.write("    " + ", ".join("{0x%02X, 0x%02X, 0x%02X}" % c for c in flat[i:i + 6]) + ",\n")
    f.write("};\n")
    f.write(f"static const uint16_t dc_palette_offset[{len(dc)}] = {{{', '.join(map(str, offs))}}};\n")
    f.write(f"static const uint8_t dc_palette_size[{len(dc)}] = {{{', '.join(str(len(c)) for _, c in dc)}}};\n")
    f.write(f"static const char *const dc_palette_names[{len(dc)}] = {{\n")
    f.write("".join(f'    "{label(n)}",\n' for n, _ in dc))
    f.write("};\n")

print(f"{len(gb)} GB palettes (default {gb[gb_default][0]}), {len(dc)} Dither Cam palettes "
      f"(default {dc[dc_default][0]}), {sum(len(c) for _, c in dc)} colours")
