"""
Generates firmware/main/icons.h and firmware/main/icons_data.h from
assets/icons/*.png - 16x16 menu row icons, one per settings concept. Edit
those PNGs (paint over the placeholders tools/gen_icon_placeholders.py made,
keep them 16x16 RGBA) then rerun this to bake them into the firmware:

    python tools/gen_icons.py

Each icon is stored as RGB565 pixels plus a 1bpp alpha mask (opaque where
the source pixel's alpha >= 128, transparent otherwise - no partial
blending, to keep display_icon() a plain conditional write like the rest of
app_display.c's framebuffer code). Order here is icon_id_t's order - add a
new (name, id) pair to ICONS to add an icon; existing ids never move as long
as entries above them aren't removed.
"""
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "assets", "icons")
PUB = os.path.join(ROOT, "firmware", "main", "icons.h")
DATA = os.path.join(ROOT, "firmware", "main", "icons_data.h")
SIZE = 16

# (C enum name, source filename stem) - see module docstring for ordering.
ICONS = [
    ("ICON_PALETTE", "palette"),
    ("ICON_DITHER", "dither"),
    ("ICON_STYLE", "style"),
    ("ICON_SCALE", "scale"),
    ("ICON_METHOD", "method"),
    ("ICON_SIZE", "size"),
    ("ICON_AMOUNT", "amount"),
    ("ICON_DENOISE", "denoise"),
    ("ICON_GALLERY", "gallery"),
    ("ICON_EXIT", "exit"),
    ("ICON_FRAME", "frame"),
]


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def load(stem):
    img = Image.open(os.path.join(SRC_DIR, f"{stem}.png")).convert("RGBA")
    if img.size != (SIZE, SIZE):
        raise SystemExit(f"{stem}.png is {img.size[0]}x{img.size[1]}, expected {SIZE}x{SIZE}")
    px = img.load()
    pixels, alpha_rows = [], []
    for y in range(SIZE):
        row_pixels, bits = [], 0
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            row_pixels.append(rgb565(r, g, b))
            if a >= 128:
                bits |= 1 << x
        pixels.append(row_pixels)
        alpha_rows.append(bits)
    return pixels, alpha_rows


def main():
    with open(PUB, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/gen_icons.py from assets/icons. Do not edit. */\n")
        f.write("#pragma once\n\n")
        f.write(f"#define ICON_W {SIZE}\n#define ICON_H {SIZE}\n\n")
        f.write("typedef enum {\n")
        for enum_name, _ in ICONS:
            f.write(f"    {enum_name},\n")
        f.write("    ICON_COUNT\n} icon_id_t;\n")

    with open(DATA, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/gen_icons.py from assets/icons. Do not edit.\n")
        f.write(" * Per icon: ICON_H rows of ICON_W RGB565 pixels, plus one alpha_bits value\n")
        f.write(" * per row (bit x set = pixel x is opaque - source alpha >= 128). */\n")
        f.write("#pragma once\n#include <stdint.h>\n\n#include \"icons.h\"\n\n")
        f.write(f"static const uint16_t icon_pixels[ICON_COUNT][{SIZE}][{SIZE}] = {{\n")
        for enum_name, stem in ICONS:
            pixels, _ = load(stem)
            f.write(f"    {{ /* {enum_name} */\n")
            for row in pixels:
                f.write("        {" + ", ".join(f"0x{v:04X}" for v in row) + "},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write(f"static const uint16_t icon_alpha[ICON_COUNT][{SIZE}] = {{\n")
        for enum_name, stem in ICONS:
            _, alpha_rows = load(stem)
            f.write("    {" + ", ".join(f"0x{v:04X}" for v in alpha_rows) + f"}}, /* {enum_name} */\n")
        f.write("};\n")

    print(f"{len(ICONS)} icon(s), {SIZE}x{SIZE} -> {PUB}, {DATA}")


if __name__ == "__main__":
    main()
